link:
  author_link: "https://www.michaelhartl.com/"
  news_link: "https://news.railstutorial.org/"
  static_pages:
    home:
      link_1: "https://www.railstutorial.org/"
    help:
      link_1: "https://www.railstutorial.org/help"
      link_2: "https://www.railstutorial.org/book"
    about:
      link_1: "https://www.railstutorial.org/"
      link_2: "https://www.learnenough.com/"
      link_3: "https://www.railstutorial.org/book"
      link_4: "https://screencasts.railstutorial.org/"
      link_5: "https://rubyonrails.org/"
